name: hover_widget
description: Quicker way to add interactive hover/tap effects to any widgets
version: 0.1.1
repository: https://github.com/gags-21/hover_widget
# author: Gagan Bhirangi <gagan.bhirangi123@gmail.com>

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
